export const mockAnalyses = [
  {
    id: "1",
    document_name: "PV AG 2024 - Résidence Les Lilas",
    created_at: "2026-03-13T10:00:00Z",
    score: 7.5,
    is_full_report: false,
    report_json: JSON.stringify({
      score: 7.5,
      summary: "Copropriété globalement bien entretenue avec quelques travaux à anticiper. La situation financière est saine.",
      address: "12 Rue des Lilas, 75020 Paris",
      generalOpinion: "Le PV d'AG révèle une copropriété bien gérée avec un syndic professionnel. Quelques travaux de ravalement sont à prévoir dans les 2 prochaines années.",
      pros: [
        "Gestion transparente et rigoureuse du syndic",
        "Fonds de travaux bien alimenté",
        "Peu de copropriétaires en impayés",
      ],
      vigilancePoints: [
        "Ravalement de façade à voter prochainement (coût estimé : 85 000€)",
        "Ascenseur vieillissant nécessitant un remplacement sous 5 ans",
      ],
      recommendations: [
        "Négocier le prix en tenant compte du ravalement imminent",
        "Demander un devis pour le remplacement de l'ascenseur",
        "Vérifier les tantièmes de charges du lot concerné",
      ],
      financialHealth: "La copropriété dispose d'un fonds de travaux de 42 000€, ce qui est satisfaisant pour un immeuble de cette taille. Les charges annuelles sont de 2 450€, en hausse de 2.1% sur un an.",
      works: [
        { description: "Ravalement de façade", status: "À voter", impact: "Élevé" },
        { description: "Peinture parties communes", status: "Voté", impact: "Faible" },
      ],
      financials: { annualCharges: 2450, chargesTrend: "+2.1%", reserveFund: "42 000 €", taxeFonciere: "1 100 €" },
      diagnostics: { dpe: "C", ges: "B", amiante: "Néant", plomb: "Néant" },
      analymoAdvice: "Ce bien présente un bon profil d'investissement. Le ravalement est un point à intégrer dans votre négociation, mais la copropriété est bien gérée et les finances sont saines. Nous recommandons d'avancer dans votre projet d'achat en négociant une décote de 5 à 8% pour couvrir les travaux à venir.",
    }),
  },
  {
    id: "2",
    document_name: "Audit Complet - 45 Avenue de la République, Lyon",
    created_at: "2026-03-07T10:00:00Z",
    score: 5.5,
    is_full_report: true,
    report_json: JSON.stringify({
      score: 5.5,
      summary: "Petite copropriété nécessitant des travaux énergétiques importants. Risque de hausse significative des charges.",
      address: "45 Avenue de la République, 69003 Lyon",
      generalOpinion: "Ce bien présente des risques financiers non négligeables liés à la performance énergétique du bâtiment et à l'insuffisance du fonds de travaux.",
      pros: [
        "Quartier dynamique et bien desservi",
        "Petite copropriété (12 lots) facilitant les prises de décision",
      ],
      vigilancePoints: [
        "DPE G - Passoire thermique, interdiction de louer sans travaux dès 2025",
        "Chaudière collective vétuste à remplacer",
        "Fonds de travaux très insuffisant (3 500€)",
      ],
      recommendations: [
        "Vérifier l'éligibilité aux aides MaPrimeRénov' pour les travaux d'isolation",
        "Demander un audit énergétique complet",
        "Prévoir un budget conséquent pour les appels de fonds à venir",
      ],
      financialHealth: "Situation préoccupante : charges en hausse de 12.4% et fonds de travaux largement insuffisant pour les projets d'isolation prévus (estimés à 45 000€).",
      works: [
        { description: "Audit énergétique", status: "En cours", impact: "Moyen" },
        { description: "Isolation par l'extérieur", status: "À voter (est. 45 000€)", impact: "Très élevé" },
      ],
      financials: { annualCharges: 1800, chargesTrend: "+12.4%", reserveFund: "3 500 €", taxeFonciere: "450 €" },
      diagnostics: { dpe: "G", ges: "F", amiante: "Présence (conduits)", plomb: "Néant" },
      analymoAdvice: "Ce bien présente des risques significatifs. L'interdiction de louer un DPE G sans travaux rend cet investissement locatif risqué. Si vous achetez pour y vivre, anticipez des appels de fonds importants dans les 2 prochaines années. Nous recommandons de négocier fortement le prix ou de considérer d'autres biens.",
    }),
  },
  {
    id: "3",
    document_name: "Diagnostics Techniques - Appartement T2 Marseille",
    created_at: "2026-03-01T10:00:00Z",
    score: 8.2,
    is_full_report: false,
    report_json: JSON.stringify({
      score: 8.2,
      summary: "Diagnostics très satisfaisants. Le bien est en excellent état technique.",
      address: "8 Boulevard Longchamp, 13001 Marseille",
      generalOpinion: "Les diagnostics révèlent un bien en très bon état. Performance énergétique correcte et aucun risque lié à l'amiante ou au plomb.",
      pros: [
        "DPE B - Très bonne performance énergétique",
        "Aucune trace d'amiante ou de plomb",
        "Installation électrique aux normes",
      ],
      vigilancePoints: [
        "Risque sismique modéré (zone 3) - normal pour la région",
      ],
      recommendations: [
        "Bien globalement sûr, pas de travaux majeurs à prévoir",
        "Vérifier l'état des menuiseries pour optimiser encore la performance",
      ],
      financialHealth: "Non applicable - analyse de diagnostics uniquement.",
      works: [],
      financials: { annualCharges: 1200, chargesTrend: "+1.5%", reserveFund: "28 000 €", taxeFonciere: "750 €" },
      diagnostics: { dpe: "B", ges: "A", amiante: "Néant", plomb: "Néant" },
      analymoAdvice: "Excellent profil technique ! Ce bien ne présente aucun risque majeur. Vous pouvez avancer sereinement dans votre projet d'achat.",
    }),
  },
];

export const exampleProperties = [
  {
    id: 1,
    address: "12 Rue de la Paix",
    city: "Paris 75002",
    type: "Appartement T3 – 68 m²",
    price: "845 000 €",
    score: 88,
    status: "Investissement Sûr",
    analysisDate: "14 Mars 2024",
    summary: "Copropriété parfaitement entretenue. Faibles charges et fonds de travaux solide. Idéal pour résidence principale ou investissement locatif.",
    positives: ["Ravalement récent (2022)", "Zéro impayé de charges", "Toiture révisée en 2023"],
    vigilance: ["Ascenseur d'origine (entretien suivi)", "Local vélo saturé"],
    financials: {
      annualCharges: 2450,
      chargesTrend: "+2.1%",
      reserveFund: "42 000 €",
      taxeFonciere: "1 100 €",
    },
    diagnostics: { dpe: "C", ges: "B", amiante: "Néant", plomb: "Néant" },
    works: [
      { year: "2022", title: "Ravalement de façade", cost: "Voté & Payé", status: "Terminé" },
      { year: "2023", title: "Révision toiture", cost: "12 000 €", status: "Terminé" },
      { year: "2025", title: "Peinture parties communes", cost: "8 000 €", status: "À l'étude" },
    ],
    alerts: [
      { title: "Règlement de copropriété", desc: "Profession libérale autorisée sous conditions.", severity: "low" },
      { title: "Charges", desc: "Légère hausse prévue suite au changement de syndic.", severity: "medium" },
    ],
  },
  {
    id: 2,
    address: "45 Avenue de la République",
    city: "Lyon 69003",
    type: "Studio – 24 m²",
    price: "185 000 €",
    score: 62,
    status: "Vigilance Requise",
    analysisDate: "12 Mars 2024",
    summary: "Petite copropriété avec des travaux énergétiques importants à prévoir. Risque de hausse des charges significatif.",
    positives: ["Quartier dynamique", "Petite copropriété (12 lots)"],
    vigilance: ["DPE G (Passoire thermique)", "Chaudière collective vétuste"],
    financials: {
      annualCharges: 1800,
      chargesTrend: "+12.4%",
      reserveFund: "3 500 €",
      taxeFonciere: "450 €",
    },
    diagnostics: { dpe: "G", ges: "F", amiante: "Présence (conduits)", plomb: "Néant" },
    works: [
      { year: "2024", title: "Audit Énergétique", cost: "2 500 €", status: "En cours" },
      { year: "2025", title: "Isolation par l'extérieur", cost: "Est. 45 000 €", status: "À voter" },
    ],
    alerts: [
      { title: "Loi Climat", desc: "Interdiction de louer dès 2025 sans travaux.", severity: "high" },
      { title: "Trésorerie", desc: "Fonds de travaux insuffisant pour les projets à venir.", severity: "high" },
    ],
  },
];
